
java_test(
    name = "LexerTest",
    srcs = ["LexerTest.java"],
    deps = [
        "//java/argon:lexer",
        "//third_party/junit4",
    ],
)

java_test(
    name = "ParserTest",
    srcs = ["ParserTest.java"],
    deps = [
        "//java/argon:lexer",
        "//java/argon:parser",
        "//third_party/junit4",
    ],
)
